"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createApp = exports.UnauthorizedError = exports.NotFoundError = exports.InternalServerError = exports.BadRequestError = exports.HttpError = exports.Methods = exports.customInjectParam = exports.customInjectFn = exports.initMethodAsync = exports.PipelineContext = exports.pipeline = exports.dynamicFactory = exports.Hooks = exports.injectLazy = exports.cache = exports.once = exports.throttle = exports.interval = exports.debounce = exports.delay = exports.bind = exports.mixins = exports.override = exports.bootstrap = exports.Injector = exports.Module = exports.module = exports.lazy = exports.Util = exports.EventDispatcher = exports.singleton = exports.define = exports.injectAliasFactory = exports.injectAlias = exports.injectArray = exports.injectDictionary = exports.injectObjectProperty = exports.injectValue = exports.aliasFactory = exports.alias = exports.injectFactoryMethod = exports.injectFactory = exports.injectParam = exports.initMethod = exports.inject = exports.factory = exports.Define = exports.pipelineType = exports.pipelineInstance = void 0;
const tslib_1 = require("tslib");
const app_1 = require("./lib/app");
const util_1 = require("./lib/util/util");
Object.defineProperty(exports, "Util", { enumerable: true, get: function () { return util_1.Util; } });
const appolo_agent_1 = require("appolo-agent");
Object.defineProperty(exports, "BadRequestError", { enumerable: true, get: function () { return appolo_agent_1.BadRequestError; } });
Object.defineProperty(exports, "HttpError", { enumerable: true, get: function () { return appolo_agent_1.HttpError; } });
Object.defineProperty(exports, "InternalServerError", { enumerable: true, get: function () { return appolo_agent_1.InternalServerError; } });
Object.defineProperty(exports, "Methods", { enumerable: true, get: function () { return appolo_agent_1.Methods; } });
Object.defineProperty(exports, "NotFoundError", { enumerable: true, get: function () { return appolo_agent_1.NotFoundError; } });
Object.defineProperty(exports, "UnauthorizedError", { enumerable: true, get: function () { return appolo_agent_1.UnauthorizedError; } });
Object.defineProperty(exports, "Hooks", { enumerable: true, get: function () { return appolo_agent_1.Hooks; } });
const appolo_engine_1 = require("appolo-engine");
Object.defineProperty(exports, "alias", { enumerable: true, get: function () { return appolo_engine_1.alias; } });
Object.defineProperty(exports, "aliasFactory", { enumerable: true, get: function () { return appolo_engine_1.aliasFactory; } });
Object.defineProperty(exports, "bind", { enumerable: true, get: function () { return appolo_engine_1.bind; } });
Object.defineProperty(exports, "bootstrap", { enumerable: true, get: function () { return appolo_engine_1.bootstrap; } });
Object.defineProperty(exports, "cache", { enumerable: true, get: function () { return appolo_engine_1.cache; } });
Object.defineProperty(exports, "debounce", { enumerable: true, get: function () { return appolo_engine_1.debounce; } });
Object.defineProperty(exports, "Define", { enumerable: true, get: function () { return appolo_engine_1.Define; } });
Object.defineProperty(exports, "define", { enumerable: true, get: function () { return appolo_engine_1.define; } });
Object.defineProperty(exports, "delay", { enumerable: true, get: function () { return appolo_engine_1.delay; } });
Object.defineProperty(exports, "EventDispatcher", { enumerable: true, get: function () { return appolo_engine_1.EventDispatcher; } });
Object.defineProperty(exports, "factory", { enumerable: true, get: function () { return appolo_engine_1.factory; } });
Object.defineProperty(exports, "initMethod", { enumerable: true, get: function () { return appolo_engine_1.initMethod; } });
Object.defineProperty(exports, "inject", { enumerable: true, get: function () { return appolo_engine_1.inject; } });
Object.defineProperty(exports, "injectAlias", { enumerable: true, get: function () { return appolo_engine_1.injectAlias; } });
Object.defineProperty(exports, "injectAliasFactory", { enumerable: true, get: function () { return appolo_engine_1.injectAliasFactory; } });
Object.defineProperty(exports, "injectArray", { enumerable: true, get: function () { return appolo_engine_1.injectArray; } });
Object.defineProperty(exports, "injectDictionary", { enumerable: true, get: function () { return appolo_engine_1.injectDictionary; } });
Object.defineProperty(exports, "injectFactory", { enumerable: true, get: function () { return appolo_engine_1.injectFactory; } });
Object.defineProperty(exports, "injectFactoryMethod", { enumerable: true, get: function () { return appolo_engine_1.injectFactoryMethod; } });
Object.defineProperty(exports, "injectLazy", { enumerable: true, get: function () { return appolo_engine_1.injectLazy; } });
Object.defineProperty(exports, "injectObjectProperty", { enumerable: true, get: function () { return appolo_engine_1.injectObjectProperty; } });
Object.defineProperty(exports, "Injector", { enumerable: true, get: function () { return appolo_engine_1.Injector; } });
Object.defineProperty(exports, "injectParam", { enumerable: true, get: function () { return appolo_engine_1.injectParam; } });
Object.defineProperty(exports, "injectValue", { enumerable: true, get: function () { return appolo_engine_1.injectValue; } });
Object.defineProperty(exports, "interval", { enumerable: true, get: function () { return appolo_engine_1.interval; } });
Object.defineProperty(exports, "lazy", { enumerable: true, get: function () { return appolo_engine_1.lazy; } });
Object.defineProperty(exports, "mixins", { enumerable: true, get: function () { return appolo_engine_1.mixins; } });
Object.defineProperty(exports, "module", { enumerable: true, get: function () { return appolo_engine_1.module; } });
Object.defineProperty(exports, "Module", { enumerable: true, get: function () { return appolo_engine_1.Module; } });
Object.defineProperty(exports, "once", { enumerable: true, get: function () { return appolo_engine_1.once; } });
Object.defineProperty(exports, "override", { enumerable: true, get: function () { return appolo_engine_1.override; } });
Object.defineProperty(exports, "singleton", { enumerable: true, get: function () { return appolo_engine_1.singleton; } });
Object.defineProperty(exports, "throttle", { enumerable: true, get: function () { return appolo_engine_1.throttle; } });
Object.defineProperty(exports, "dynamicFactory", { enumerable: true, get: function () { return appolo_engine_1.dynamicFactory; } });
Object.defineProperty(exports, "pipeline", { enumerable: true, get: function () { return appolo_engine_1.pipeline; } });
Object.defineProperty(exports, "PipelineContext", { enumerable: true, get: function () { return appolo_engine_1.PipelineContext; } });
Object.defineProperty(exports, "initMethodAsync", { enumerable: true, get: function () { return appolo_engine_1.initMethodAsync; } });
Object.defineProperty(exports, "customInjectFn", { enumerable: true, get: function () { return appolo_engine_1.customInjectFn; } });
Object.defineProperty(exports, "customInjectParam", { enumerable: true, get: function () { return appolo_engine_1.customParam; } });
Object.defineProperty(exports, "pipelineInstance", { enumerable: true, get: function () { return appolo_engine_1.pipelineInstance; } });
Object.defineProperty(exports, "pipelineType", { enumerable: true, get: function () { return appolo_engine_1.pipelineType; } });
var route_1 = require("./lib/routes/route");
Object.defineProperty(exports, "Route", { enumerable: true, get: function () { return route_1.Route; } });
var controller_1 = require("./lib/controller/controller");
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return controller_1.Controller; } });
var staticController_1 = require("./lib/controller/staticController");
Object.defineProperty(exports, "StaticController", { enumerable: true, get: function () { return staticController_1.StaticController; } });
tslib_1.__exportStar(require("./lib/decorators/decorators"), exports);
var middleware_1 = require("./lib/middleware/middleware");
Object.defineProperty(exports, "Middleware", { enumerable: true, get: function () { return middleware_1.Middleware; } });
var staticMiddleware_1 = require("./lib/middleware/staticMiddleware");
Object.defineProperty(exports, "StaticMiddleware", { enumerable: true, get: function () { return staticMiddleware_1.StaticMiddleware; } });
var app_2 = require("./lib/app");
Object.defineProperty(exports, "App", { enumerable: true, get: function () { return app_2.App; } });
var events_1 = require("./lib/interfaces/events");
Object.defineProperty(exports, "Events", { enumerable: true, get: function () { return events_1.Events; } });
var routeModel_1 = require("./lib/routes/routeModel");
Object.defineProperty(exports, "RouteModel", { enumerable: true, get: function () { return routeModel_1.RouteModel; } });
function createApp(options) {
    return new app_1.App(options);
}
exports.createApp = createApp;
function default_1(options) {
    return new app_1.App(options);
}
exports.default = default_1;
;
//# sourceMappingURL=index.js.map