"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const validator = require("joi");
exports.validator = validator;
const app_1 = require("./lib/app");
const util_1 = require("./lib/util/util");
exports.Util = util_1.Util;
const appolo_context_1 = require("appolo-context");
exports.Context = appolo_context_1.Context;
const appolo_agent_1 = require("appolo-agent");
exports.BadRequestError = appolo_agent_1.BadRequestError;
exports.HttpError = appolo_agent_1.HttpError;
exports.InternalServerError = appolo_agent_1.InternalServerError;
exports.Methods = appolo_agent_1.Methods;
exports.NotFoundError = appolo_agent_1.NotFoundError;
exports.UnauthorizedError = appolo_agent_1.UnauthorizedError;
exports.Hooks = appolo_agent_1.Hooks;
const appolo_engine_1 = require("appolo-engine");
exports.alias = appolo_engine_1.alias;
exports.aliasFactory = appolo_engine_1.aliasFactory;
exports.bind = appolo_engine_1.bind;
exports.bootstrap = appolo_engine_1.bootstrap;
exports.cache = appolo_engine_1.cache;
exports.debounce = appolo_engine_1.debounce;
exports.Define = appolo_engine_1.Define;
exports.define = appolo_engine_1.define;
exports.delay = appolo_engine_1.delay;
exports.EventDispatcher = appolo_engine_1.EventDispatcher;
exports.factory = appolo_engine_1.factory;
exports.initMethod = appolo_engine_1.initMethod;
exports.inject = appolo_engine_1.inject;
exports.injectAlias = appolo_engine_1.injectAlias;
exports.injectAliasFactory = appolo_engine_1.injectAliasFactory;
exports.injectArray = appolo_engine_1.injectArray;
exports.injectDictionary = appolo_engine_1.injectDictionary;
exports.injectFactory = appolo_engine_1.injectFactory;
exports.injectFactoryMethod = appolo_engine_1.injectFactoryMethod;
exports.injectLazy = appolo_engine_1.injectLazy;
exports.injectObjectProperty = appolo_engine_1.injectObjectProperty;
exports.Injector = appolo_engine_1.Injector;
exports.injectParam = appolo_engine_1.injectParam;
exports.injectValue = appolo_engine_1.injectValue;
exports.interval = appolo_engine_1.interval;
exports.lazy = appolo_engine_1.lazy;
exports.mixins = appolo_engine_1.mixins;
exports.module = appolo_engine_1.module;
exports.Module = appolo_engine_1.Module;
exports.once = appolo_engine_1.once;
exports.override = appolo_engine_1.override;
exports.singleton = appolo_engine_1.singleton;
exports.throttle = appolo_engine_1.throttle;
exports.dynamicFactory = appolo_engine_1.dynamicFactory;
var route_1 = require("./lib/routes/route");
exports.Route = route_1.Route;
var controller_1 = require("./lib/controller/controller");
exports.Controller = controller_1.Controller;
var staticController_1 = require("./lib/controller/staticController");
exports.StaticController = staticController_1.StaticController;
tslib_1.__exportStar(require("./lib/decorators/decorators"), exports);
var middleware_1 = require("./lib/middleware/middleware");
exports.Middleware = middleware_1.Middleware;
var staticMiddleware_1 = require("./lib/middleware/staticMiddleware");
exports.StaticMiddleware = staticMiddleware_1.StaticMiddleware;
var app_2 = require("./lib/app");
exports.App = app_2.App;
var events_1 = require("./lib/interfaces/events");
exports.Events = events_1.Events;
var routeModel_1 = require("./lib/routes/routeModel");
exports.RouteModel = routeModel_1.RouteModel;
function createApp(options) {
    return new app_1.App(options);
}
exports.createApp = createApp;
function default_1(options) {
    return new app_1.App(options);
}
exports.default = default_1;
;
//# sourceMappingURL=index.js.map